name: riverpod_keyboard
description: "Riverpod experience"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_midi_pro: 3.1.6
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mockito: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Kids_Piano.sf2